gnosisguild/zodiac-modifier-roles

- contracts/Roles.sol
- test/Roles.spec.ts
This PR adds custom errors, rather than require statements.
> Add custom errors

- contracts/Roles.sol
- test/Roles.spec.ts
> More-tests

- .github/workflows/dev-cd.yaml
- .github/workflows/prod-release-deploy.yaml
- packages/app/.fleek.dev.json
- packages/app/.fleek.prod.json
I also set the necessary secrets on this repo that get used as env variables during the build.
> Sets up deploy action and fleek config

- .github/workflows/dev-cd.yaml
- .github/workflows/prod-release-deploy.yaml
I went ahead and put the graph service ids in the config. Let me know if you prefer another way, there didn't seem to be a compelling reason not to.
> adds graph build/deploy to actions

- packages/app/src/components/modals/PendingChanges.tsx
- packages/app/src/services/rolesModifierContract.ts
> Issue-#52-display_summary_of_queued_changes

- packages/app/src/components/views/Header/Header.tsx
- packages/app/src/components/views/Header/HeaderBox.tsx
- packages/app/src/components/views/Role/RoleMenu.tsx
- packages/app/src/components/views/Role/RoleNoTarget.tsx
- packages/app/src/services/rolesModifierContract.ts
> Issue_#104-submit_transaction_without_execution

- packages/app/src/components/views/Role/RoleContext.tsx
- packages/app/src/components/views/Role/targets/TargetConfiguration.tsx
Bug fixes related to adding and editing targets
Closes #108
Closes #117
> Bug fixes related to adding and editing targets

- packages/app/src/components/views/Header/ConnectWalletBox.tsx
- packages/app/src/components/views/Header/HeaderAddressBox.tsx
closed #80 
Following this UI: https://www.figma.com/file/h2nRHyTfrJb2hhXME6FDX4/Zodiac-Roles-Modifier?node-id=341%3A21606
> Add disconnect button

- packages/app/src/components/views/Role/RoleMenu.tsx
closed #94 
URL to test: http://localhost:3000/#/rin:0xbdfdf9b21e18883a107d185ec80733c402357fdc/roles/7223
Steps to test:
- Remove or add some member or target
- The before action should show the 'View Pending Changes' Button
UI
> Only show pending changes when there are changes to show.

- packages/subgraph/src/permissions.mapping.ts
> [subgraph] ScopeFunction bug

- packages/app/src/components/commons/layout/Dashboard.tsx
> Parameters causing overflow issues on smaller screens

- packages/app/src/components/views/Role/RoleMenu.tsx
- packages/app/src/components/views/Role/targets/TargetConfiguration.tsx
- packages/app/src/components/views/Role/targets/TargetFunction.tsx
- packages/app/src/components/views/Role/targets/TargetFunctionParams.tsx
- packages/app/src/services/rolesModifierContract.ts
- packages/app/src/typings/role.ts
Closes #153
Closes #154 
Closes #155
Other fixes:
- Convert ParameterType correctly when scoping
> App various bugfixes

- packages/app/src/components/views/Role/RoleContext.tsx
- packages/app/src/components/views/Role/targets/TargetFunctionParams.tsx
- packages/app/src/services/rolesModifierContract.ts
- packages/app/src/typings/role.ts
> Bug smasher 2

- packages/app/package.json
- packages/app/src/components/views/Role/targets/TargetFunction.tsx
- packages/app/src/components/views/Role/targets/TargetFunctionList.tsx
- packages/app/src/components/views/Role/targets/TargetFunctionParams.tsx
- packages/app/src/services/explorer.ts
- packages/app/src/utils/explorer.ts
- packages/app/yarn.lock
closes #177 
- handle proxies and fetch ABI of implementation contract
- if an allowed function is not found in the ABI, we still show it under its sighash
> app: proxy handling

- packages/app/src/components/views/Role/targets/ParamConditionInput.tsx
- packages/app/src/components/views/Role/targets/ParamConditionInputValue.tsx
- packages/app/src/components/views/Role/targets/TargetFunctionParams.tsx
> app: Improve the displaying of raw parameter values

- packages/app/src/components/views/Role/targets/ParamConditionInput.tsx
- packages/app/src/components/views/Role/targets/ParamConditionInputValue.tsx
- packages/app/src/components/views/Role/targets/TargetFunctionList.tsx
- packages/app/src/components/views/Role/targets/TargetFunctionParams.tsx
- packages/app/src/utils/conditions.ts
closes #171 
based off #181, so should only be merged after that one
> app: support for `oneOf` param scopings

- packages/app/components/permissions/TargetItem/index.tsx
- packages/app/package.json
- yarn.lock
Role view is currently broken for this route https://roles.gnosisguild.org/gno%3A0x39B37934Bf81d87683984961266dD27385bC3f9a/roles/test-role
this fix makes the prop passing to `FunctionPermissionItem` more explicit. I thought there might be a version conflict with wagmi, this was not the case, but including the update here anyway.
> Fix component error and wagmi upgrade

- packages/docs/pages/_meta.json
- packages/docs/theme.config.tsx
- packages/docs/theme.module.css
> add badge and app link to docs

- packages/app/components/permissions/TargetItem/addressLabels.json
- packages/app/components/permissions/TargetItem/index.tsx
Check it out here: https://zodiac-roles-app-git-address-labels-gnosis-guild.vercel.app/gno:0x39B37934Bf81d87683984961266dD27385bC3f9a/roles/test-role
> Label target addresses

- packages/app/app/[mod]/roles/[role]/breadcrumbs.tsx
- packages/app/app/[mod]/roles/[role]/diff/[hash]/breadcrumbs.tsx
- packages/app/app/[mod]/roles/[role]/diff/[hash]/page.module.css
- packages/app/app/[mod]/roles/[role]/diff/[hash]/page.tsx
- packages/app/app/permissions/[chain]/[hash]/breadcrumbs.tsx
- packages/app/app/permissions/[chain]/[hash]/diff/[hashRight]/breadcrumbs.tsx
- packages/app/app/permissions/[chain]/[hash]/diff/[hashRight]/page.module.css
- packages/app/app/permissions/[chain]/[hash]/diff/[hashRight]/page.tsx
- packages/app/app/permissions/[chain]/[hash]/page.module.css
- packages/app/app/permissions/[chain]/[hash]/page.tsx
- packages/app/components/Layout/index.tsx
- packages/app/components/Layout/style.module.css
- packages/app/components/permissions/ConditionView/index.tsx
- packages/app/components/permissions/ConditionView/style.module.css
- packages/app/components/permissions/DiffBox/index.tsx
- packages/app/components/permissions/PermissionsDiff/diff.ts
- packages/app/components/permissions/PresetItem/index.tsx
- packages/app/components/permissions/TargetItem/FunctionPermissionItem.tsx
- packages/app/components/permissions/TargetItem/index.tsx
- packages/app/components/permissions/TargetItem/style.module.css
- packages/sdk/src/annotations/index.ts
- packages/sdk/src/permissions/utils.ts
- some styling fixes for the diff view
- fix diff highlighting (was a bit broken after the recent UI improvements)
- example: [/eth:0xBd1099dFD3c11b65FB4BB19A350da2f5B61Efb0d/roles/BALANCER-MANAGER/diff/USYo5yY5aE89Q100Zv5IGjy177hqNAvxQbZv5vR4lU](https://zodiac-roles-app-git-diff-view-fixes-gnosis-guild.vercel.app/eth:0xBd1099dFD3c11b65FB4BB19A350da2f5B61Efb0d/roles/BALANCER-MANAGER/diff/USYo5yY5aE89Q100Zv5IGjy177hqNAvxQbZv5vR4lU)
- fix diff display for wildcard permissions
- example: [/eth:0xBd1099dFD3c11b65FB4BB19A350da2f5B61Efb0d/roles/BALANCER-MANAGER/diff/yqdCiJrM5DBkl6CSNdU2aQHiS2FBcz7Ko1kGtuguuE](https://zodiac-roles-app-git-diff-view-fixes-gnosis-guild.vercel.app/eth:0xBd1099dFD3c11b65FB4BB19A350da2f5B61Efb0d/roles/BALANCER-MANAGER/diff/yqdCiJrM5DBkl6CSNdU2aQHiS2FBcz7Ko1kGtuguuE) …
> Diff view fixes

- packages/app/app/abi.ts
- packages/app/components/permissions/TargetItem/index.tsx
- packages/app/components/permissions/TargetItem/style.module.css
- packages/app/components/permissions/annotations.ts
- packages/app/package.json
- yarn.lock
scrap whatsabi for direct fetches from etherscan. this fixes issues when whatsabi picked from the wrong alternative of potential auto-guessed signatures.
the PR also improves the proxy detection by using the evm-proxy-detection package for more extensive coverage and better performance.
we now show contract names and indicate proxy contracts
> app: More reliable ABI fetching, better target labels

- README.md
- packages/sdk/package.json
- packages/sdk/src/chains.ts
- packages/subgraph/package.json
- packages/subgraph/src/permissions.mapping.ts
- yarn.lock
fixed bug: when adding a condition to a previously wildcarded function, the `wildcarded` state was not reset to `false`
> fix subgraph bug

- packages/app/components/RoleView/fetching.ts
- packages/app/components/RolesList/index.tsx
- packages/deployments/package.json
- packages/deployments/src/fetchRole.ts
- packages/deployments/src/fetchRolesMod.ts
- packages/deployments/src/types.ts
- packages/docs/pages/sdk/getting-started.mdx
- packages/sdk/src/annotations/index.ts
- packages/sdk/src/members.ts
- packages/sdk/src/targets/applyTargets.ts
- packages/sdk/src/utils/groupBy.ts
include function selectors, execution options and wildcarded flag in the fetchRolesMod query
> deployments: better role summary

- README.md
- packages/deployments/package.json
- packages/deployments/src/chains.ts
- packages/deployments/src/fetchRolesMod.ts
- packages/sdk/package.json
- packages/subgraph/src/helpers.ts
- packages/subgraph/src/periphery.mapping.ts
fix an issue that caused unwrap adapter updates to not be indexed
> subgraph: fix update adapter

- packages/app/app/[mod]/roles/[role]/diff/[hash]/page.module.css
- packages/app/app/[mod]/roles/[role]/diff/[hash]/page.tsx
- packages/app/app/api/permissions/route.ts
- packages/app/app/api/permissions/types.ts
- packages/app/app/permissions/[chain]/[hash]/diff/[hashRight]/page.module.css
- packages/app/app/permissions/[chain]/[hash]/diff/[hashRight]/page.tsx
- packages/app/components/ApplyUpdate/index.tsx
- packages/app/components/DiffView/index.tsx
- packages/app/components/DiffView/style.module.css
- packages/app/components/RoleView/index.tsx
- packages/app/components/members/MembersDiff/diff.ts
- packages/app/components/members/MembersDiff/index.tsx
- packages/app/components/members/MembersDiff/style.module.css
- packages/app/components/members/MembersList/index.tsx
- packages/app/components/members/MembersList/style.module.css
- packages/app/components/permissions/schema.ts
- packages/app/ui/TabGroup/index.tsx
- packages/app/ui/TabGroup/style.module.css
- packages/docs/pages/index.mdx
- packages/docs/pages/sdk/getting-started.mdx
- packages/sdk/package.json
- packages/sdk/src/annotations/applyAnnotations.ts
- packages/sdk/src/api.ts
- packages/sdk/src/index.ts
- packages/sdk/src/members.ts
- packages/sdk/src/permissions/index.ts
- packages/sdk/src/types.ts
- allow including a members list in the post to the /permission API
- include members in diff view
- apply member updates
- export a `postRole` function as part of the sdk
- some documentation edits
> allow posting members as part of role updates

- packages/evm/hardhat.config.ts
- packages/evm/package.json
- yarn.lock
This PR adds support for the **BoB Sepolia** testnet in Hardhat configuration. The newly introduced network allows deploying and verifying smart contracts on BoB's Sepolia blockchain.
- Added `bob-sepolia` network configuration to `hardhat.config.ts`.
- Included `bob-sepolia` under the `etherscan.apiKey` configuration using a placeholder key.
- Extended `customChains` configuration to support contract verification for BoB Sepolia.
The following contracts were successfully deployed on **BoB Sepolia**:
- 🚀 AvatarIsOwnerOfERC721@2.1.0: Successfully verified at https://explorer-bob-sepolia-dm6uw0yhh3.t.conduit.xyz/address/0x91B1bd7BCC5E623d5CE76b0152253499a9C819d1
- 🚀 Integrity@2.1.0: Successfully verified at https://explorer-bob-sepolia-dm6uw0yhh3.t.conduit.xyz/address/0x6a6Af4b16458Bc39817e4 …
> feat: introduce bob sepolia

- packages/sdk/package.json
- packages/sdk/src/conditions/checkConditionIntegrity.test.ts
- packages/sdk/src/conditions/checkConditionIntegrity.ts
we rejected a condition that only sets an allowance on the eth value. this fixes it
> fix: overly strict condition integrity check
